name: Hello, world demo

on:
  push:
    branches:
    - main
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: environment
        required: true
jobs:
  Build:
    name: Build job
    runs-on: ubuntu-latest
    steps:
      - run: I'm building ...
  Test:
    runs-on: ubuntu-latest
    if: github.event_name == "workflow_dispatch"
    needs: [Build]
    environment: Test
    steps:
    - run: echo "🧪 Testing..."

