name: Hello, world demo

on:
  push:
    branches:
    - main
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: environment
        required: true
jobs:
  job1:
    name: First job
    runs-on: ubuntu-latest
    steps:
      - name: say hellp
        run: echo Hello, world!
      
  
